/**
 * @module strongai/strongAiIssueRenderer
 * Renders StrongAI issues/*.md drafts from GuardDog review results.
 */
// Copyright (c) 2025 Jon Verrier

import { IFinding, IReviewResult } from '../schemas/finding';
import { IStrongAiPlatformTarget } from '../schemas/strongAiPlatforms';

export interface IStrongAiRenderedIssue {
   title: string;
   markdown: string;
   fileName: string;
}

/**
 * Builds a StrongAI inbox issue markdown file from a GuardDog review result.
 * @param target - Platform package target
 * @param result - Filtered GuardDog review result
 */
export function renderStrongAiIssue(
   target: IStrongAiPlatformTarget,
   result: IReviewResult
): IStrongAiRenderedIssue {
   const title = `GuardDog architecture review: ${target.id}`;
   const lines: string[] = [];

   lines.push('**Status:** open');
   lines.push('**Type:** proposal');
   lines.push(
      '**GitHub:** _(added by `tools/build/scripts/sync-issues-to-github.sh` after first sync)_'
   );
   lines.push(
      '**Superseded by:** _(leave empty until promoted to `features/NNNN-...`; then set path and change **Status** to `superseded`, **Type** to `pointer`)_'
   );
   lines.push('');
   lines.push(`# ${title}`);
   lines.push('');
   lines.push('## Summary');
   lines.push('');
   lines.push(
      `GuardDog reviewed \`${target.packagePath}\` against \`${target.packagePath}/${target.designFile}\` ` +
         `and found **${result.summary.findingCount}** finding(s) ` +
         `(overall risk: **${result.summary.overallRisk}**; ` +
         `high: ${result.summary.highSeverityCount}, critical: ${result.summary.criticalSeverityCount}).`
   );
   lines.push('');
   lines.push(
      'This issue proposes incremental architecture improvements for the package. ' +
         'Treat GuardDog as an architecture radar: triage findings before promoting work to `features/`.'
   );
   lines.push('');
   lines.push('## Scope');
   lines.push('');
   lines.push(`- **Packages:** \`${target.packagePath}\` (${target.displayName})`);
   lines.push('- **Likely size:** single PR | multi-PR | promotes to feature');
   lines.push('- **Source:** GuardDog cloud review (one issue per package)');
   lines.push('');

   if (result.summary.mainThemes.length > 0) {
      lines.push('## Main themes');
      lines.push('');
      for (const theme of result.summary.mainThemes) {
         lines.push(`- ${theme}`);
      }
      lines.push('');
   }

   lines.push('## Proposed improvements');
   lines.push('');
   if (result.findings.length === 0) {
      lines.push(
         '*No findings matched the configured severity and impact filters. Re-run with lower thresholds if needed.*'
      );
      lines.push('');
   } else {
      for (const finding of result.findings) {
         lines.push(...renderFindingSection(finding));
         lines.push('');
      }
   }

   lines.push('## Acceptance criteria');
   lines.push('');
   lines.push('- [ ] Triage each finding (accept, defer, or reject with rationale)');
   lines.push('- [ ] File follow-up PRs or promote accepted items to `features/` as needed');
   lines.push('- [ ] Re-run GuardDog on the package after remediations and attach the new report');
   lines.push('');
   lines.push('## Notes');
   lines.push('');
   lines.push(`- Design file: \`${target.packagePath}/${target.designFile}\``);
   lines.push(`- GuardDog generated at: \`${result.generatedAt}\``);
   if (result.sampledReview) {
      lines.push(
         '- Review was **sampled** (some ranked source files omitted due to token budgets).'
      );
   }
   lines.push('- Labels suggestion for sync: `proposal`');
   lines.push('');
   lines.push(
      '_Generated by GuardDog StrongAI platform cloud review. Spec and checklist: edit this markdown file in git._'
   );
   lines.push('');

   return {
      title,
      markdown: lines.join('\n'),
      fileName: `${target.issueSlug}.md`
   };
}

function renderFindingSection(finding: IFinding): string[] {
   const lines: string[] = [];
   lines.push(`### ${finding.id} — ${finding.title}`);
   lines.push('');
   lines.push(
      `- **Severity / impact / confidence:** ${finding.severity} / ${finding.impact} / ${finding.confidence}`
   );
   lines.push(`- **Principle:** ${finding.principle}`);
   lines.push(`- **Risk:** ${finding.risk}`);
   lines.push(
      `- **Blast radius:** ${finding.blastRadius.rating} — ${finding.blastRadius.reasoning}`
   );
   lines.push(`- **Recommendation:** ${finding.recommendation}`);
   lines.push(`- **Fitness function:** ${finding.possibleFitnessFunction}`);

   if (finding.evidence.length > 0) {
      lines.push('- **Evidence:**');
      for (const item of finding.evidence) {
         const location = [item.file, item.directory].filter(Boolean).join(' / ');
         lines.push(`  - ${location ? `\`${location}\`: ` : ''}${item.observation}`);
      }
   }

   if (finding.facts.length > 0) {
      lines.push('- **Facts:**');
      for (const fact of finding.facts) {
         lines.push(`  - ${fact}`);
      }
   }

   if (finding.inferences.length > 0) {
      lines.push('- **Inferences:**');
      for (const inference of finding.inferences) {
         lines.push(`  - ${inference}`);
      }
   }

   return lines;
}
